#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    startHouse = s
    endHouse = t
    house = list(range(startHouse, endHouse+1))
    appleTree = a
    orangeTree = b
    nApples = 0
    nOranges = 0

    #print(sum[1 for x in apples if (x+a) >= s and (x+a) <= t])
    #print(sum[1 for y in oranges if (y+a) >= s and (y+a) <= t])
    
    for apple in apples:
        if appleTree + apple >= startHouse and appleTree + apple <= endHouse:
            nApples +=1
    
    for orange in oranges: 
        if orangeTree + orange >= startHouse and orangeTree + orange <= endHouse:
            nOranges += 1
  
    print(nApples)
    print(nOranges)    
if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
