#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    gatoA = 0
    gatoB = 0
    if x >= z:
        gatoA = x - z
    else:
        gatoA = z - x
    if y >= z:
        gatoB = y - z
    else:
        gatoB = z - y
    
    if gatoA < gatoB:
        return 'Cat A'
    elif gatoB < gatoA:
        return 'Cat B'
    else:
        return 'Mouse C'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
