#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'circularArrayRotation' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER k
#  3. INTEGER_ARRAY queries
#

#we have to reorganize a, k times and return the elements in the indexes in queries
#to do that, I take the last element from the list and add it in the beginning k times
#in the end, I get the elements in given indexes and put it in a list
#I return the list because the outside program is dividing the list and printint the numbers

def circularArrayRotation(a, k, queries):
    lista=[]
    for i in range(0,k):
        a.insert(0, a.pop())
    for elem in queries:
        lista.append(a[elem])
    return lista
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    q = int(first_multiple_input[2])

    a = list(map(int, input().rstrip().split()))

    queries = []

    for _ in range(q):
        queries_item = int(input().strip())
        queries.append(queries_item)

    result = circularArrayRotation(a, k, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
