#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    valley = 0
    seaLevel = True
    level = 0

    for i in range(0, len(path)):
        seaLevel = False
        
        if path[i] == 'U':
            level += 1
        elif path[i] == 'D':
            level -= 1

        if level == 0:
            seaLevel = True

        if seaLevel == True and path[i] == 'U':
            valley += 1
            seaLevel = False
            ds = False

    return valley

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
