#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dayOfProgrammer' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER year as parameter.
#

def dayOfProgrammer(year):
    message = ''
    if year >= 1700 and year <= 1917:
        if year%4 == 0:
            message = '12.09.' + str(year)
        else:
            message = '13.09.' + str(year)
    
    elif year == 1918:
        message = '26.09.1918'
    
    elif year >= 1919:
        if year%400 == 0 or year%4 == 0 and year%100 != 0:
            message = '12.09.' + str(year)
        else:
            message = '13.09.' + str(year)
        
    return(message)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
