#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    matriz = arr
    somaDiagonal1 = 0
    somaDiagonal2 = 0
    contador1 = 0
    contador2 = len(matriz)-1
    while contador1 < len(matriz):
        somaDiagonal1 += matriz[contador1][contador1]
        somaDiagonal2 += matriz[contador1][contador2]
        contador1 += 1
        contador2 -= 1
    
    final = 0
    final = abs(somaDiagonal1 - somaDiagonal2)
    return final

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
