#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'divisibleSumPairs' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER k
#  3. INTEGER_ARRAY ar
#

def divisibleSumPairs(n, k, ar):
    lista = []
    indicea = 0
    contador = 1
    indiceb = contador
    
    while indicea <= n:
        while indiceb < n:
            if (ar[indicea] + ar[indiceb]) % k == 0:
                lista.append((indicea, indiceb))
            indiceb += 1
        indicea += 1
        contador += 1
        indiceb = contador
    
    return (len(lista))
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
