#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    dicionario = {}
    pares = 0
    for elem in ar:
        if elem not in dicionario:
            dicionario[elem] = 1
        else:
            dicionario[elem] += 1
    
    for item in dicionario:
        if dicionario[item] >= 2:
            pares += dicionario[item]//2
    
    return(pares)
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
